package:
  name: wrapt
  version: 1.16.0
  top-level:
    - wrapt
source:
  url: https://files.pythonhosted.org/packages/ff/21/abdedb4cdf6ff41ebf01a74087740a709e2edb146490e4d9beea054b0b7a/wrapt-1.16.0-py3-none-any.whl
  sha256: 6906c4100a8fcbf2fa735f6059214bb13b97f75b1a61777fcf6432121ef12ef1
about:
  home: https://github.com/GrahamDumpleton/wrapt
  PyPI: https://pypi.org/project/wrapt
  summary: Module for decorators, wrappers and monkey patching.
  license: BSD
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
