import { Section } from '@src/app/core/data/database/interfaces/section';
import { FieldMeasure } from './types';
import { v4 as uuidv4 } from 'uuid';

export const createInitialMeasureData = (
  section: Section | null,
  name: string
): FieldMeasure => {
  return {
    uuid: uuidv4(),
    name: name || '',
    span: null,
    longitude: null,
    latitude: null,
    altitude: null,
    azimuth: null,
    date: null,
    time: null,
    season: null,
    ambientTemperature: null,
    windSpeed: null,
    windSpeedUnit: null,
    windDirection: null,
    skyCover: null,
    calculationMethod: 'papoto',
    leftSupport: null,
    spanLength: null,
    measuredElevationDifference: null,
    HL: null,
    H1: null,
    H2: null,
    H3: null,
    HR: null,
    VL: null,
    V1: null,
    V2: null,
    V3: null,
    VR: null,
    cableHAccDistance: null,
    cableVerticalAccAngle: null,
    calculationType: 'parametre',
    cableTangentAngle: null,
    lengthBetweenSightGD: null,
    elevationDifferenceBetweenSightGD: null,
    xSight1: null,
    xSight2: null,
    xSight3: null,
    ySight1: null,
    ySight2: null,
    ySight3: null,
    transit: null,
    windIncidence: null,
    windIncidenceMode: null,
    diffuseSolarFlux: 123,
    directSolarFlux: null,
    diffuseDirectSolarFlux: 246,
    diffusedSolarFlux: null,
    measuredDiffusedPlusDirectSolarFlux: null,
    measuredDiffusedSolarFlux: null,
    diffusedPlusDirectSolarFlux: null,
    updateMode15C: null,
    parameterPapoto: null,
    parameterUncertaintyPapoto: null,
    cableTemperature15C: null,
    cableTemperatureUncertainty15C: null,
    line: section?.cable_name || null,
    voltage: section?.voltage_idr || null,
    spanType: section?.type || null,
    phaseNumber: section?.electric_phase_number || null,
    numberOfConductors: section?.cables_amount || null,
    cableName: section?.cable_name || null
  };
};
