import { FieldMeasure, CalculationResults } from './types';

export const leftSupportOption = [
  { label: '12', value: '12' },
  { label: '13', value: '13' },
  { label: '14', value: '14' },
  { label: '15', value: '15' }
];

export const INITIAL_MEASURE_DATA: FieldMeasure = {
  uuid: '',
  name: '',
  link: 'Line 225kV Rougemontier - Tourbe #1',
  voltage: '123 kV',
  spanType: 'Phase',
  phaseNumber: 3,
  numberOfConductors: 3,
  span: [11, 12],
  longitude: null,
  latitude: null,
  altitude: 123.09876523,
  azimuth: null,
  date: new Date(),
  time: new Date(),
  season: 'summer',
  ambientTemperature: null,
  windSpeed: null,
  windSpeedUnit: 'kmh',
  windDirection: 'North',
  skyCover: '8 (cloudy)',
  calculationMethod: 'papoto',
  leftSupport: '',
  spanLength: null,
  measuredElevationDifference: null,
  HL: null,
  H1: null,
  H2: null,
  H3: null,
  HR: null,
  VL: null,
  V1: null,
  V2: null,
  V3: null,
  VR: null,
  cableHAccDistance: null,
  cableVerticalAccAngle: null,
  calculationType: 'parametre',
  cableTangentAngle: null,
  lengthBetweenSightGD: null,
  elevationDifferenceBetweenSightGD: null,
  xSight1: null,
  xSight2: null,
  xSight3: null,
  ySight1: null,
  ySight2: null,
  ySight3: null,
  cableName: 'ASTER570',
  transit: null,
  windIncidence: 47,
  windIncidenceMode: 'auto',
  diffuseSolarFlux: 123,
  directSolarFlux: 123,
  diffuseDirectSolarFlux: 246,
  diffusedSolarFlux: 248,
  measuredDiffusedPlusDirectSolarFlux: null,
  measuredDiffusedSolarFlux: null,
  diffusedPlusDirectSolarFlux: null,
  updateMode15C: 'auto',
  parameterPapoto: 1700,
  parameterUncertaintyPapoto: 12,
  cableTemperature15C: 45,
  cableTemperatureUncertainty15C: 3
};

export const INITIAL_CALCULATION_RESULTS: CalculationResults = {
  parameter: null,
  parameterUncertainty: null,
  parameter12: null,
  parameter23: null,
  parameter13: null,
  criteria05: null,
  sideDGreaterThan2m: null,
  sideDValid: null,
  validMeasurement: null,
  cableTemperature: null,
  cableTemperatureUncertainty: null,
  cableSolarFlux: null,
  parameter15CMinusUncertainty: null,
  parameter15C: null,
  parameter15CPlusUncertainty: null
};
