import { FieldMeasureData, CalculationResults } from './types';

export const INITIAL_MEASURE_DATA: FieldMeasureData = {
  measureName: '',
  line: 'Line 225kV Rougemontier - Tourbe #1',
  voltage: 123,
  spanType: 'Phase',
  phaseNumber: 3,
  numberOfConductors: 3,
  span: '12-13',
  longitude: 123.12345678,
  latitude: 123.87654321,
  altitude: 123.09876523,
  azimuth: 123,
  date: new Date(),
  time: '10:13',
  season: 'summer',
  ambientTemperature: null,
  windSpeed: null,
  windSpeedUnit: 'kmh',
  windDirection: 'North',
  skyCover: '8 (cloudy)',
  calculationMethod: 'papoto',
  leftSupport: '',
  spanLength: null,
  measuredElevationDifference: null,
  HG: null,
  H1: null,
  H2: null,
  H3: null,
  HD: null,
  VG: null,
  V1: null,
  V2: null,
  V3: null,
  VD: null,
  cableHAccDistance: null,
  cableVerticalAccAngle: null,
  calculationType: 'parametre',
  cableTangentAngle: null,
  lengthBetweenSightGD: null,
  elevationDifferenceBetweenSightGD: null,
  xSight1: null,
  xSight2: null,
  xSight3: null,
  ySight1: null,
  ySight2: null,
  ySight3: null,
  cableName: 'ASTER570',
  transit: 'A',
  windIncidence: 47,
  windIncidenceMode: 'auto',
  diffuseSolarFlux: 123,
  directSolarFlux: 123,
  diffuseDirectSolarFlux: 246,
  measuredSolarFlux: 248,
  updateMode15C: 'auto',
  parameterFapolo: 1700,
  parameterUncertaintyFapolo: 12,
  cableTemperature15C: 45,
  cableTemperatureUncertainty15C: 3
};

export const INITIAL_CALCULATION_RESULTS: CalculationResults = {
  parameter: null,
  parameterUncertainty: null,
  parameter12: null,
  parameter23: null,
  parameter13: null,
  criteria05: null,
  sideDGreaterThan2m: null,
  sideDValid: null,
  validMeasurement: null,
  cableTemperature: null,
  cableTemperatureUncertainty: null,
  cableSolarFlux: null,
  parameter15CMinusUncertainty: null,
  parameter15C: null,
  parameter15CPlusUncertainty: null
};
