package:
  name: pandera
  version: 0.21.1
  top-level:
    - pandera
source:
  url: https://files.pythonhosted.org/packages/9b/1c/63fac4a86797b584132532cfab7295321103255930b96e516ab9101ffa90/pandera-0.21.1-py3-none-any.whl
  sha256: cb6323952815ab82484bd8371f71d0b609a9cd0f515a7b91b2c076871b4db387
about:
  home: https://github.com/pandera-dev/pandera
  PyPI: https://pypi.org/project/pandera
  summary:
    A light-weight and flexible data validation and testing tool for statistical
    data objects.
  license: MIT
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
